#!/bin/sh

USER=bibi
HOST=192.168.0.102
DIR=/home/bibi/public   # the directory where your web site files should go

hugo && rsync -avz --delete public/ ${USER}@${HOST}:${DIR} # this will delete everything on the server that's not in the local public folder
