baseURL = 'kingillmusic.com'
languageCode = 'en-us'
title = 'Stream My Music Ad-Free | Experimental, Trap, EDM & Chill'
theme = 'ill-type-theme'

[params]
	favicon = '/favicon.png'

[taxonomies]
	tag = 'tags'
