#!/bin/sh

# This script extracts amplitude information using audiowaveform tool.
# https://github.com/bbc/audiowaveform

find mp3 -name "*.ogg" | while read track; do
    # Define the output JSON path
    outfile="waveforms/${track#mp3/}"
    outfile="${outfile%.ogg}.json"
    
    # Create the output directory if it doesn't exist
    mkdir -p "$(dirname "$outfile")"
  
    # Check if the JSON file already exists
    if [ -f "$outfile" ]; then
        echo "Skipping $track (JSON already exists)"
    else
        echo "Processing $track -> $outfile"
        audiowaveform -i "$track" -o "$outfile"
	fi
done
